service: aws-node-express-api
frameworkVersion: '3'

custom:
  serverless-offline:
    httpPort: 4000
    noPrependStageInUrl: true
  env: ${file(./env.json)}
provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  timeout: 15
  httpApi:
    cors: true

functions:
  api:
    handler: server.handler
    environment:
      DB_NAME: ${${self:custom.env}:DB_NAME}
      DB_USER: ${${self:custom.env}:DB_USER}
      DB_PASS: ${${self:custom.env}:DB_PASS}
      DB_HOST: ${${self:custom.env}:DB_HOST}
      DB_PORT: ${${self:custom.env}:DB_PORT}
    events:
      - httpApi: '*'



plugins:
  - serverless-offline
  - serverless-esbuild
  - serverless-dotenv-plugin