service: aws-node-express-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  timeout: 15
  httpApi:
    cors: true

functions:
  api:
    handler: server.handler
    events:
      - httpApi: '*'


plugins:
  - serverless-offline