service: aws-node-express-api
frameworkVersion: '3'

custom:
  serverless-offline:
    httpPort: 3001
    noPrependStageInUrl: true
    
provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  timeout: 15
  httpApi:
    cors: true

functions:
  api:
    handler: server.handler
    environment:
      DB_NAME: ${file(./env.json):DB_NAME}
      DB_USER: ${file(./env.json):DB_USER}
      DB_PASS: ${file(./env.json):DB_PASS}
      DB_HOST: ${file(./env.json):DB_HOST}
      DB_PORT: ${file(./env.json):DB_PORT}
    events:
      - httpApi: '*'



plugins:
  - serverless-offline
  - serverless-esbuild
  - serverless-dotenv-plugin