service: first-api
frameworkVersion: '3'

custom: 
  webpack:
    webpackConfig: './serverless.ts'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1

plugins: 
  - serverless-esbuild


functions:
  hi:
    timeout: 30
    handler: src/functions/index.ts