service: aws-node-express-api
frameworkVersion: '3'

custom:
  serverless-offline:
    httpPort: 4000
    noPrependStageInUrl: true

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  timeout: 15
  httpApi:
    cors: true

functions:
  api:
    handler: server.handler
    environment: ${file(env.json)}
    events:
      - httpApi: '*'



plugins:
  - serverless-offline
  - serverless-esbuild
  - serverless-dotenv-plugin