service: first-api,
frameworkVersion: '3'
custom: 
  webpack:
    webpackConfig: './serverless.ts'
  SECRETS: ${file(./secret.js):getSecrets}
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
plugins: 
  - serverless-esbuild
functions:
  hi:
    timeout: 20  
    environment:
      DB_HOSTNAME: ${self:custom.SECRETS.DB_HOSTNAME}
      DB_USERNAME: ${self:custom.SECRETS.DB_USERNAME}
      DB_PASSWORD: ${self:custom.SECRETS.DB_PASSWORD}